### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by daizch** [sindresorhus/gulp-autoprefixer#100]
I am getting an error when I want to inline css files into html file.

Here is my simple example which can throw the below error.
https://github.com/daizch/autoprefix-example

<pre>
[16:32:22] Using gulpfile ~/workplace/github/autoprefixer-example/gulpfile.js
[16:32:22] Starting 'build'...
[16:32:22] Starting 'clean'...
[16:32:22] Finished 'clean' after 5.85 ms
[16:32:22] Starting 'compile'...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (/Users/daizecheng/workplace/github/autoprefixer-example/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:288:12)
    at DestroyableTransform.Writable.write (/Users/daizecheng/workplace/github/autoprefixer-example/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:332:20)
    at write (/Users/daizecheng/workplace/github/autoprefixer-example/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/daizecheng/workplace/github/autoprefixer-example/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/daizecheng/workplace/github/autoprefixer-example/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at emitReadable_ (/Users/daizecheng/workplace/github/autoprefixer-example/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/daizecheng/workplace/github/autoprefixer-example/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/daizecheng/workplace/github/autoprefixer-example/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
</pre>

**Comment by sindresorhus** [comment]
I don't think this is relevant anymore.
