### ISSUE TITLE
Unexpected token, problem when build

### ISSUE THREAD

**Issue by LadIQe** [sindresorhus/gulp-autoprefixer#115]
Hello, when I tried to run npm run gulp build, I get this error

```
/Users/unknown/Desktop/test-project/node_modules/gulp-autoprefixer/index.js:21
		(async () => {
		       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/unknown/Desktop/test-project/build/compile.js:15:20)
    at Module._compile (module.js:570:32)

npm ERR! Darwin 19.5.0
npm ERR! argv "/Users/unknown/.nvm/versions/node/v6.9.2/bin/node" "/Users/unknown/.nvm/versions/node/v6.9.2/bin/npm" "run" "gulp" "build"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
```

this is gulpfile.js

```
'use strict';

var requireDir = require('require-dir');

requireDir('./build', {recurse: true});
```

Its test project, nothing fancy.

Thank you

**Comment by sindresorhus** [comment]
Upgrade your Node.js version.

**Comment by LadIQe** [comment]
I wish to, but its recommended to use max 6.9.2 according to manual

**Comment by LadIQe** [comment]
ok used 14.4.0 and now it works, why to write manuals when they are bad. Closing
