### ISSUE TITLE
Firefox ESR Queries cause an unhandled error

### ISSUE THREAD

**Issue by anilnatha** [sindresorhus/gulp-autoprefixer#35]
#### Background:

I have the following autoprefixer setup in a gulp task:

```Javascript
.pipe($.autoprefixer({browsers: ['Explorer > 10','Firefox ESR > 25', 'Safari > 8']}))
```
#### Issue:

After autoprefixer executes, the following error is being generated 
```
Error in plugin 'gulp-autoprefixer'
Error
    at c:\path\to\project\node_modules\gulp-autoprefixer\index.js:51:7
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
[gulp] Site\src\less\styles.less
[09:08:55] Plumber found unhandled error:
 Error in plugin 'gulp-autoprefixer'
Error
    at c:\path\to\project\node_modules\gulp-autoprefixer\index.js:51:7
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
```

Now if I change the Firefox query to be either of the following, the call is successful:
```Javascript
.pipe($.autoprefixer({browsers: ['Explorer > 10','Firefox ESR', 'Safari > 8']}))
```
```Javascript
.pipe($.autoprefixer({browsers: ['Explorer > 10','Firefox > 25', 'Safari > 8']}))
```

#### System Setup:

node: 0.12.3
npm: 2.9.1
gulp-autoprefixer: 2.3.0

**Comment by kevva** [comment]
`Firefox ESR > 25` is not a supported browser. See [this](https://github.com/ai/browserslist) list for a list of available browsers.
