### ISSUE TITLE
nodejs 4.0.0 support

### ISSUE THREAD

**Issue by prog666** [sindresorhus/gulp-autoprefixer#44]
events.js:141
throw er; // Unhandled 'error' event
^

Error: no writecb in Transform class
at afterTransform (/projectfolder/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:95:33)
at Immediate.TransformState.afterTransform (/projectfolder/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
at Immediate.immediate._onImmediate (timers.js:423:18)
at processImmediate as _immediateCallback

**Comment by sindresorhus** [comment]
Passing on Node.js 4: https://travis-ci.org/sindresorhus/gulp-autoprefixer

Happy to look into it further if you submit a failing test.

**Comment by prog666** [comment]
i can give you my gulpfile, tried to read your test, not really getting it

**Comment by prog666** [comment]
my bad, was using old version, it sucks that npm does not update it to latest every time i do npm update

**Comment by prog666** [comment]
actually, i did update it to version 3.0.1 and problem isn't gone

**Comment by prog666** [comment]
```javascript
var gulp                = require('gulp'),
    browserSync         = require('browser-sync'),
    reload              = browserSync.reload,
    gulpif              = require('gulp-if'),
    stylus              = require('gulp-stylus'),
    autoprefixer        = require('gulp-autoprefixer'),
    combineMediaQueries = require('gulp-combine-media-queries'),
    addsrc              = require('gulp-add-src'),
    filter              = require('gulp-filter'),
    mainBowerFiles      = require('main-bower-files'),
    minify              = require('gulp-minify-css'),
    cssBase64           = require('gulp-css-base64'),
    concat              = require('gulp-concat'),
    nib                 = require('nib'),
    // sourcemaps          = require('gulp-sourcemaps'),
    config              = require('../config').stylus;


gulp.task('stylus', function () {
    return gulp.src(config.src)
        // .pipe(sourcemaps.init())
        .pipe(stylus({use: nib}))
        .pipe(autoprefixer())
        .pipe(combineMediaQueries())
        .pipe(addsrc.prepend(mainBowerFiles()))
        .pipe(cssBase64({maxWeightResource: config.base64.maxWeight}))
        .pipe(filter('*.css'))
        .pipe(concat(config.resultName))
        .pipe(gulpif(global.production, minify({compatibility: config.minify.compatibility, noAdvanced: true})))
        // .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest(config.dest))
        .pipe(reload({stream: true}));
});
```

**Comment by prog666** [comment]
```json
{
  "name": "prototype",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "wdio"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babelify": "^6.1.2",
    "chai": "^3.2.0",
    "del": "^2.0.2",
    "gulp": "^3.8.11",
    "gulp-add-src": "^0.2.0",
    "gulp-autoprefixer": "^3.0.1",
    "gulp-browserify": "^0.5.1",
    "gulp-combine-media-queries": "^0.2.0",
    "gulp-concat": "^2.4.3",
    "gulp-connect": "^2.2.0",
    "gulp-css-base64": "^1.3.1",
    "gulp-filter": "^3.0.1",
    "gulp-if": "^1.2.5",
    "gulp-jade": "^1.1.0",
    "gulp-jscs": "^2.0.0",
    "gulp-jscs-stylish": "^1.1.0",
    "gulp-jshint": "^1.11.2",
    "gulp-minify-css": "^1.2.1",
    "gulp-notify": "^2.2.0",
    "gulp-sftp": "^0.1.4",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-stylus": "^2.0.0",
    "gulp-tinypng": "^1.0.2",
    "gulp-uglify": "^1.1.0",
    "main-bower-files": "^2.5.0",
    "nib": "^1.1.0",
    "require-dir": "^0.3.0",
    "run-sequence": "^1.0.2"
  },
  "dependencies": {
    "animated-scrollto": "^1.1.0",
    "future-tabs": "^1.2.0",
    "marmottajax": "^2.0.2"
  }
}
```
