### ISSUE TITLE
Getting Promise errors

### ISSUE THREAD

**Issue by KvdM** [sindresorhus/gulp-autoprefixer#45]
I tried the following code:

    var gulp = require('gulp');
    var sourcemaps = require('gulp-sourcemaps');
    var autoprefixer = require('gulp-autoprefixer');
    var concat = require('gulp-concat');
     
    
    var gulp = require('gulp');
    var autoprefixer = require('gulp-autoprefixer');
    
    gulp.task('default', function () {
        return gulp.src('src/styles.css')
            .pipe(autoprefixer({
                browsers: ['last 2 versions'],
                cascade: false
            }))
            .pipe(gulp.dest('dist'));
    });

But I'm constantly getting errors like this:

    /Users/krisvandermast/gulptests/b/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:152
            this.processing = new Promise(function (resolve, reject) {
                                  ^
    ReferenceError: Promise is not defined
        at LazyResult.async (/Users/krisvandermast/gulptests/b/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:152:31)
        at LazyResult.then (/Users/krisvandermast/gulptests/b/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:75:21)
        at DestroyableTransform._transform (/Users/krisvandermast/gulptests/b/node_modules/gulp-autoprefixer/index.js:28:13)
        at DestroyableTransform.Transform._read (/Users/krisvandermast/gulptests/b/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
        at DestroyableTransform.Transform._write (/Users/krisvandermast/gulptests/b/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
        at doWrite (/Users/krisvandermast/gulptests/b/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
        at writeOrBuffer (/Users/krisvandermast/gulptests/b/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
        at DestroyableTransform.Writable.write (/Users/krisvandermast/gulptests/b/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
        at write (/Users/krisvandermast/gulptests/b/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
        at flow (/Users/krisvandermast/gulptests/b/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)

What is going on and most important: how can I get around it?

**Comment by sindresorhus** [comment]
You need to upgrade Node.js.

**Comment by bioball** [comment]
It would be nice to be able to use our own version of a promise. Perhaps something like:

```js
var autoprefixer = require('gulp-autoprefixer');
autoprefixer.Promise = require('bluebird');
```

**Comment by sindresorhus** [comment]
```js
global.Promise = require('bluebird');
```

**Comment by bioball** [comment]
@sindresorhus would you take a PR for what I'm suggesting? Happy to do one

**Comment by sindresorhus** [comment]
No

**Comment by ptarjan** [comment]
This makes me sad that this happened in a point release. Can you at least bump the major version number (backwards compat break) so people using SEMVER don't break from one build to the next?

**Comment by pvfhv** [comment]
npm WARN engine gulp-autoprefixer@3.0.2: wanted: {"node":">=0.12.0"} (current: {"node":"v0.10.26","npm":"1.4.3"})

**Comment by sindresorhus** [comment]
> This makes me sad that this happened in a point release.

You're wrong. This happened in the 3.0.0 major release.
