### ISSUE TITLE
Missing Error Message

### ISSUE THREAD

**Issue by lukepolo** [sindresorhus/gulp-autoprefixer#52]
/var/www/html/mint/20151202151933/node_modules/gulp-util/lib/PluginError.js:73
  if (!this.message) throw new Error('Missing error message');
                           ^
Error: Missing error message
    at new PluginError (/var/www/html/mint/20151202151933/node_modules/gulp-util/lib/PluginError.js:73:28)
    at DestroyableTransform.logError (/var/www/html/mint/20151202151933/node_modules/gulp-sass/index.js:168:17)
    at DestroyableTransform.emit (events.js:117:20)
    at afterTransform (/var/www/html/mint/20151202151933/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:75:19)
    at TransformState.afterTransform (/var/www/html/mint/20151202151933/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:59:12)
    at errorM (/var/www/html/mint/20151202151933/node_modules/gulp-sass/index.js:123:14)
    at DestroyableTransform._transform (/var/www/html/mint/20151202151933/node_modules/gulp-sass/index.js:151:16)
    at DestroyableTransform.Transform._read (/var/www/html/mint/20151202151933/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/var/www/html/mint/20151202151933/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/var/www/html/mint/20151202151933/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:333:12)

Any Ideas?

**Comment by sindresorhus** [comment]
The error is coming from gulp-sass.
