### ISSUE TITLE
Cannot read property 'value' of undifined

### ISSUE THREAD

**Issue by yashilanka** [sindresorhus/gulp-autoprefixer#53]
i got this error when i start gulp, i tried to reinstall all the packages, update node version but nothing seems to work..

node -v
v5.3.0

npm -v
3.3.12

events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'value' of undefined
    at /Users/Yashi/Data/Code/HTMLCSS/HCM/node_modules/autoprefixer/lib/transition.js:109:57
    at Array.filter (native)
    at Transition.remove (/Users/Yashi/Data/Code/HTMLCSS/HCM/node_modules/autoprefixer/lib/transition.js:106:23)
    at /Users/Yashi/Data/Code/HTMLCSS/HCM/node_modules/autoprefixer/lib/processor.js:153:39
    at /Users/Yashi/Data/Code/HTMLCSS/HCM/node_modules/postcss/lib/container.js:88:34
    at /Users/Yashi/Data/Code/HTMLCSS/HCM/node_modules/postcss/lib/container.js:73:26
    at Rule.each (/Users/Yashi/Data/Code/HTMLCSS/HCM/node_modules/postcss/lib/container.js:60:22)
    at Rule.walk (/Users/Yashi/Data/Code/HTMLCSS/HCM/node_modules/postcss/lib/container.js:72:21)
    at /Users/Yashi/Data/Code/HTMLCSS/HCM/node_modules/postcss/lib/container.js:76:32
    at Root.each (/Users/Yashi/Data/Code/HTMLCSS/HCM/node_modules/postcss/lib/container.js:60:22)

**Comment by sindresorhus** [comment]
That error is coming from autoprefixer, not this plugin. Open an issue over there instead.
