### ISSUE TITLE
Error: no writecb in Transform class at afterTransform

### ISSUE THREAD

**Issue by rossjcooper** [sindresorhus/gulp-autoprefixer#65]
All of a sudden I am now receiving the following error when I try to run gulp or gulp watch when a sass file is modified, it works fine for js compiling.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: no writecb in Transform class
    at afterTransform (project_path\node_modules\laravel-elixir\node_modules\gulp-autoprefixer\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:95:33)
    at Immediate.TransformState.afterTransform (project_path\node_modules\laravel-elixir\node_modules\gulp-autoprefixer\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at Immediate.immediate._onImmediate (timers.js:435:18)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I have also submitted a [similar issue](https://github.com/laravel/elixir/issues/574) to the laravel-elixer package but it looks like the problem actually come from this package. I am using Node-v4.4.7 and I have tried updating, clearing cache and reinstalling my deps with no luck.

**Comment by dmmarmol** [comment]
Same issue here. Suddenly happened to me without install any new dependency or package.

**Comment by rossjcooper** [comment]
I solved this by updating my laravel-elixir package to the next major version it looks like this issue has been fixed in newer versions.
