### ISSUE TITLE
Getting an error on compile

### ISSUE THREAD

**Issue by jessewallace** [sindresorhus/gulp-autoprefixer#76]
I'm getting an error that hasn't happened with other projects I've started before.  Any clue to whats going on here:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected token < in JSON at position 16
    at Object.parse (native)
    at new SourceMapConsumer (/Users/jessewallace/dev/projects/CMS/develop/wp-content/plugins/amp-styles/node_modules/source-map/lib/source-map-consumer.js:17:22)
    at PreviousMap.consumer (/Users/jessewallace/dev/projects/CMS/develop/wp-content/plugins/amp-styles/node_modules/postcss/lib/previous-map.js:69:34)
    at new Input (/Users/jessewallace/dev/projects/CMS/develop/wp-content/plugins/amp-styles/node_modules/postcss/lib/input.js:84:28)
    at parse (/Users/jessewallace/dev/projects/CMS/develop/wp-content/plugins/amp-styles/node_modules/postcss/lib/parse.js:21:17)
    at new LazyResult (/Users/jessewallace/dev/projects/CMS/develop/wp-content/plugins/amp-styles/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (/Users/jessewallace/dev/projects/CMS/develop/wp-content/plugins/amp-styles/node_modules/postcss/lib/processor.js:117:12)
    at DestroyableTransform._transform (/Users/jessewallace/dev/projects/CMS/develop/wp-content/plugins/amp-styles/node_modules/gulp-autoprefixer/index.js:20:31)
    at DestroyableTransform.Transform._read (/Users/jessewallace/dev/projects/CMS/develop/wp-content/plugins/amp-styles/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/jessewallace/dev/projects/CMS/develop/wp-content/plugins/amp-styles/node_modules/readable-stream/lib/_stream_transform.js:147:83)
```

**Comment by caleyshemc** [comment]
+1
