### ISSUE TITLE
After upgrading - no longer works with gulp-sass

### ISSUE THREAD

**Issue by michaelBenin** [sindresorhus/gulp-autoprefixer#81]
Hello, 

After upgrading to the latest today this stopped working: 

```
gulp.task('sass-dev', function sassDev() {
  const targetProps = config.styles.main;
  const { cssDest, stylesSrc, sassConf, autoprefixerBrowsers } = targetProps;

  return gulp.src(stylesSrc)
    .pipe(sourcemaps.init())
    .pipe(sass(sassConf).on('error', sass.logError))
    .pipe(autoprefixer(autoprefixerBrowsers))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(cssDest))
    .pipe(livereload({ file: 'http://localhost:3000/dist/static/css/main.css' }));
});
```

```
events.js:154
      throw er; // Unhandled 'error' event
      ^
TypeError: this is not a typed array.
    at Function.from (native)
    at /Users/mbenin/Projects/fc-2017-app/node_modules/gulp-autoprefixer/index.js:25:27
    at run (/Users/mbenin/Projects/fc-2017-app/node_modules/karma/node_modules/core-js/modules/es6.promise.js:87:22)
    at /Users/mbenin/Projects/fc-2017-app/node_modules/karma/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/Users/mbenin/Projects/fc-2017-app/node_modules/karma/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickDomainCallback (node.js:423:13)
```

**Comment by sindresorhus** [comment]
Note the Node.js version requirement: https://github.com/sindresorhus/gulp-autoprefixer/blob/51886049f1b2bf1e3ac0631ef2a48137f4acfe10/package.json#L13

**Comment by Yoann53** [comment]
Same to me

**Comment by kaatula** [comment]
That is perfectly reproducible with node 5.9.1
Looks like requirement is not true

**Comment by SirDev** [comment]
This is also reproducible in node 8.4.0, so something is still wrong.

**Comment by xumix** [comment]
Same here!

**Comment by bernig** [comment]
Same here :(

**Comment by fgrs** [comment]
same issue with node 6.10.0
