### ISSUE TITLE
Does not handle 'major versions'

### ISSUE THREAD

**Issue by tylercrosse** [sindresorhus/gulp-autoprefixer#88]
The option 'last 2 major versions' errors out with `BrowserslistError: Unknown browser major`. The same option works fine via webpack. 

```
    .pipe(autoprefixer({
      browsers: [
        'last 2 major versions'
      ]
    }))
```

Here's the stack trace:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^
BrowserslistError: Unknown browser major
    at checkName (/Users/tcrosse/dev/web-strategy/te-landing-page/node_modules/browserslist/index.js:339:20)
    at Function.select (/Users/tcrosse/dev/web-strategy/te-landing-page/node_modules/browserslist/index.js:484:18)
    at /Users/tcrosse/dev/web-strategy/te-landing-page/node_modules/browserslist/index.js:226:33
    at Array.forEach (<anonymous>)
    at browserslist (/Users/tcrosse/dev/web-strategy/te-landing-page/node_modules/browserslist/index.js:208:11)
    at Browsers.parse (/Users/tcrosse/dev/web-strategy/te-landing-page/node_modules/autoprefixer/lib/browsers.js:61:16)
    at new Browsers (/Users/tcrosse/dev/web-strategy/te-landing-page/node_modules/autoprefixer/lib/browsers.js:52:30)
    at loadPrefixes (/Users/tcrosse/dev/web-strategy/te-landing-page/node_modules/autoprefixer/lib/autoprefixer.js:67:24)
    at plugin (/Users/tcrosse/dev/web-strategy/te-landing-page/node_modules/autoprefixer/lib/autoprefixer.js:78:24)
    at LazyResult.run (/Users/tcrosse/dev/web-strategy/te-landing-page/node_modules/postcss/lib/lazy-result.js:270:20)
```

"gulp-autoprefixer": "^4.0.0"

**Comment by sindresorhus** [comment]
Open an issue here instead: https://github.com/ai/browserslist
